import tokens
import json

import pickle
import os.path
import re

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import httplib2

def get_values_from_spreadsheet(spreadsheet_id, range_name, concatenate=False):
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    credentials = get_credentials(scopes)

    try:
        service = build('sheets', 'v4', credentials=credentials)

        # Call the Sheets API
        sheet = service.spreadsheets()
        result = sheet.values().get(spreadsheetId=spreadsheet_id, range=range_name).execute()
        values = result.get('values', [])

        if not values:
            print('No data found.')
            return

        if concatenate:
            result = []
            [result.extend(x) for x in values]
            values = result
        
        return values
    
    except HttpError as err:
        print(err)


def alter_spreadsheet(spreadsheet_id, location_name, new_value):
    scopes = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
    credentials = get_credentials(scopes)

    try:
        service = build('sheets', 'v4', credentials=credentials)

        # Call the Sheets API
        sheet = service.spreadsheets()
        result = sheet.values().update(spreadsheetId=spreadsheet_id, range=location_name, valueInputOption='RAW', body = new_value).execute()
        
        return True
    
    except HttpError as err:
        print(err)


    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first time.

    # On the other hand, credentials.json stores our app's tokens to be allowed to communicate
    # with the google servers - i.e. how google knows to trust this app.
    # Provided you have these, you can request tokens for users.
        
    # This function will get those user's access and refresh tokens.
def get_credentials(scopes):
    creds = None

    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', scopes)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            #was getting error here "Refresh Error, invalid_grant". 
            #this is because google kills the refresh token after 6 months
            #https://developers.google.com/identity/protocols/oauth2#expiration
            except:
                print("Attempting to refresh the credentials did not succeed.\nGenerating new credentials.")
                os.remove('token.json') #TODO: This wasn't successfully deleting the token file, which then
                # needs to be regenerated by the code below in this case
                # print(os.path.exists('token.json'))
                # If this is causing errors, just manually delete token.json and rerun
        else:
            flow = InstalledAppFlow.from_client_secrets_file('credentials.json', scopes)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            print("User token was regenerated")
            token.write(creds.to_json())

    return creds


#given the name of a cell as a string, return the string for the letter code for its column,
#and the integer number for its row
def find_row_col(cell):
    i = 0
    while(cell[i].isalpha()):
        i += 1

    return cell[:i], int(cell[i:])




